/**
 * Mutable option state shared by the option files, like og
 * opttbl.c's globals. Defaults mirror og's option table.
 */
export const opt = {
  howSearch: 2,
  bufSpace: 64,
  autoBuffers: 1,
  clearRepaint: 0,
  knowDumb: 0,
  quitAtEof: 0,
  forceOpen: 0,
  quitIfOneScreen: 0,
  hiliteSearch: 2,
  backScroll: -1,
  jumpTarget: 0,
  jumpFraction: -1,
  shiftFraction: -1,
  statusCol: 0,
  quitOnIntr: 0,
  useLessopen: 1,
  prType: 0,
  linenums: 1,
  quiet: 0,
  // og's default: caret ALL escape sequences (user revoked the old
  // ctldisp=2 divergence 2026-07-24 — full og parity, -R for ANSI)
  ctldisp: 0,
  squeeze: 0,
  tagsFile: 'tags',
  bsMode: 0,
  showAttn: 0,
  tabStops: [] as number[],
  tabDefault: 8,
  noInit: 0,
  forwScroll: -1,
  quoteOpen: '"',
  quoteClose: '"',
  tildes: 1,
  noKeypad: 0,
  followName: 0,
  useBackslash: 0,
  rscrollChar: '>',
  rscrollAttr: 's' as 'n' | 's' | 'd' | 'u' | 'k',
  noHistDups: 0,
  mouseMode: 0,
  mouseReverse: 0,
  oldBot: 0,
  wheelLines: 1,
  permaMarks: 0,
  linenumWidth: 7,
  statusColWidth: 2,
  incrSearch: 0,
  useColor: 0,
  headerLines: 0,
  headerCols: 0,
  headerStart: 0,
  nonumHeaders: 0,
  nosearchHeaderLines: 0,
  nosearchHeaderCols: 0,
  wantFileSize: 0,
  noVbell: 0,
  noEditWarn: 0,
  noShell: 0,
  exitFollowOnClose: 0,
  showPreprocError: 0,
  redrawOnQuit: 0,
  noPaste: 0,
  hiliteTarget: 0,
  intrChar: '\x18',
  autosave: '-',
  matchShift: 0,
  // og defaults --match-shift to half the screen width
  // (match_shift_fraction = NUM_FRAC_DENOM/2)
  matchShiftFraction: 500000,
  emouse: 0,
  statusLine: 0,
  stopOnFormFeed: 0,
  pastEof: 0,
  modelines: 0,
  procBackspace: 0,
  procTab: 0,
  procReturn: 0,
  wordwrap: 0,
  appliedGutter: 0,
  // $LESS_IS_MORE: POSIX more compatibility, like og's less_is_more
  lessIsMore: 0,
};
