/**
 * og's lesskey action NAMES against the numeric codes a compiled file
 * carries - `lesskey_parse.c`'s cmdnames/editnames tables resolved
 * through `cmd.h`.
 *
 * The pager itself never needs this: reading a binding only has to
 * reach an action, which `ACTION_CODES` already does. WRITING one
 * does, because the byte in the file is og's code and nothing else,
 * and so does rendering a binary back as source. Both directions live
 * here so they cannot drift apart.
 *
 * GENERATED from the vendored less/ source (707x) by
 * `tools/gen-lesskey-codes.py`. Regenerate rather than edit.
 */

/** A_EXTRA: OR'd into the action byte when an extra string follows. */
export const A_EXTRA = 0x80;

/** EV_OK: the #env section's action byte, always with A_EXTRA. */
export const EV_OK = 0x01;

/** #command action names, like og's cmdnames[]. */
export const COMMAND_CODES: Record<string, number> = {
  'back-bracket':        36,
  'back-line':           2,
  'back-line-force':     30,
  'back-newline':        61,
  'back-screen':         3,
  'back-screen-force':   22,
  'back-scroll':         4,
  'back-search':         5,
  'back-window':         34,
  'clear-mark':          62,
  'clear-search':        70,
  'debug':               8,
  'digit':               6,
  'display-flag':        7,
  'display-option':      7,
  'end':                 16,
  'end-scroll':          59,
  'examine':             9,
  'filter':              55,
  'first-cmd':           10,
  'firstcmd':            10,
  'flush-repaint':       11,
  'forw-bell-hilite':    77,
  'forw-bracket':        35,
  'forw-forever':        50,
  'forw-line':           12,
  'forw-line-force':     29,
  'forw-newline':        60,
  'forw-screen':         13,
  'forw-screen-force':   40,
  'forw-scroll':         14,
  'forw-search':         15,
  'forw-until-hilite':   56,
  'forw-window':         33,
  'goto-end':            16,
  'goto-end-buffered':   57,
  'goto-line':           17,
  'goto-mark':           18,
  'goto-pos':            51,
  'help':                19,
  'index-file':          38,
  'invalid':             102,
  'left-scroll':         41,
  'mouse':               64,
  'mouse6':              68,
  'next-file':           20,
  'next-tag':            53,
  'no-scroll':           58,
  'noaction':            101,
  'osc8-forw-search':    71,
  'osc8-back-search':    72,
  'osc8-jump':           74,
  'osc8-open':           73,
  'percent':             21,
  'pipe':                37,
  'prev-file':           23,
  'prev-tag':            54,
  'pshell':              69,
  'quit':                24,
  'remove-file':         52,
  'repaint':             25,
  'repaint-flush':       11,
  'repeat-search':       43,
  'repeat-search-all':   44,
  'reverse-search':      45,
  'reverse-search-all':  46,
  'right-scroll':        42,
  'set-mark':            26,
  'set-mark-bottom':     63,
  'shell':               27,
  'status':              28,
  'toggle-flag':         47,
  'toggle-option':       47,
  'undo-hilite':         39,
  'version':             31,
  'visual':              32,
};

/** #line-edit action names, like og's editnames[]. */
export const EDIT_ACTION_CODES: Record<string, number> = {
  'back-complete':   18,
  'backspace':       1,
  'delete':          8,
  'down':            14,
  'end':             10,
  'expand':          15,
  'forw-complete':   17,
  'home':            9,
  'insert':          7,
  'invalid':         102,
  'kill-line':       2,
  'abort':           20,
  'left':            4,
  'literal':         19,
  'mouse':           21,
  'mouse6':          22,
  'noaction':        101,
  'right':           3,
  'up':              13,
  'word-backspace':  11,
  'word-delete':     12,
  'word-left':       5,
  'word-right':      6,
};

/**
 * A code back to ONE name, for rendering a binary as source.
 *
 * og lets several names share a code - "end" and "goto-end" are both
 * A_GOEND - so this keeps the first og lists, which is also the first
 * alphabetically. Any of them compiles back to the same byte.
 */
export const COMMAND_NAMES: Record<number, string> = {
  2:    'back-line',
  3:    'back-screen',
  4:    'back-scroll',
  5:    'back-search',
  6:    'digit',
  7:    'display-flag',
  8:    'debug',
  9:    'examine',
  10:   'first-cmd',
  11:   'flush-repaint',
  12:   'forw-line',
  13:   'forw-screen',
  14:   'forw-scroll',
  15:   'forw-search',
  16:   'end',
  17:   'goto-line',
  18:   'goto-mark',
  19:   'help',
  20:   'next-file',
  21:   'percent',
  22:   'back-screen-force',
  23:   'prev-file',
  24:   'quit',
  25:   'repaint',
  26:   'set-mark',
  27:   'shell',
  28:   'status',
  29:   'forw-line-force',
  30:   'back-line-force',
  31:   'version',
  32:   'visual',
  33:   'forw-window',
  34:   'back-window',
  35:   'forw-bracket',
  36:   'back-bracket',
  37:   'pipe',
  38:   'index-file',
  39:   'undo-hilite',
  40:   'forw-screen-force',
  41:   'left-scroll',
  42:   'right-scroll',
  43:   'repeat-search',
  44:   'repeat-search-all',
  45:   'reverse-search',
  46:   'reverse-search-all',
  47:   'toggle-flag',
  50:   'forw-forever',
  51:   'goto-pos',
  52:   'remove-file',
  53:   'next-tag',
  54:   'prev-tag',
  55:   'filter',
  56:   'forw-until-hilite',
  57:   'goto-end-buffered',
  58:   'no-scroll',
  59:   'end-scroll',
  60:   'forw-newline',
  61:   'back-newline',
  62:   'clear-mark',
  63:   'set-mark-bottom',
  64:   'mouse',
  68:   'mouse6',
  69:   'pshell',
  70:   'clear-search',
  71:   'osc8-forw-search',
  72:   'osc8-back-search',
  73:   'osc8-open',
  74:   'osc8-jump',
  77:   'forw-bell-hilite',
  101:  'noaction',
  102:  'invalid',
};

/** The same, for the #line-edit section. */
export const EDIT_ACTION_NAMES: Record<number, string> = {
  1:    'backspace',
  2:    'kill-line',
  3:    'right',
  4:    'left',
  5:    'word-left',
  6:    'word-right',
  7:    'insert',
  8:    'delete',
  9:    'home',
  10:   'end',
  11:   'word-backspace',
  12:   'word-delete',
  13:   'up',
  14:   'down',
  15:   'expand',
  17:   'forw-complete',
  18:   'back-complete',
  19:   'literal',
  20:   'abort',
  21:   'mouse',
  22:   'mouse6',
  101:  'noaction',
  102:  'invalid',
};
