/**
 * less's lesskey action NAMES against the numeric codes a compiled file
 * carries - `lesskey_parse.c`'s cmdnames/editnames tables resolved
 * through `cmd.h`.
 *
 * The pager itself never needs this: reading a binding only has to
 * reach an action, which `ACTION_CODES` already does. WRITING one
 * does, because the byte in the file is less's code and nothing else,
 * and so does rendering a binary back as source. Both directions live
 * here so they cannot drift apart.
 *
 * GENERATED from the vendored less/ source (707x) by
 * `tools/gen-lesskey-codes.py`. Regenerate rather than edit.
 */

/** A_EXTRA: OR'd into the action byte when an extra string follows. */
export const A_EXTRA = 0x80;

/** EV_OK: the #env section's action byte, always with A_EXTRA. */
export const EV_OK = 0x01;

/** #command action names, like less's cmdnames[]. */
export const COMMAND_CODES: Record<string, number> = {
  'back-bracket':        36,
  'back-line':           2,
  'back-line-force':     30,
  'back-newline':        61,
  'back-screen':         3,
  'back-screen-force':   22,
  'back-scroll':         4,
  'back-search':         5,
  'back-window':         34,
  'clear-mark':          62,
  'clear-search':        70,
  'debug':               8,
  'digit':               6,
  'display-flag':        7,
  'display-option':      7,
  'end':                 16,
  'end-scroll':          59,
  'examine':             9,
  'filter':              55,
  'first-cmd':           10,
  'firstcmd':            10,
  'flush-repaint':       11,
  'forw-bell-hilite':    77,
  'forw-bracket':        35,
  'forw-forever':        50,
  'forw-line':           12,
  'forw-line-force':     29,
  'forw-newline':        60,
  'forw-screen':         13,
  'forw-screen-force':   40,
  'forw-scroll':         14,
  'forw-search':         15,
  'forw-until-hilite':   56,
  'forw-window':         33,
  'goto-end':            16,
  'goto-end-buffered':   57,
  'goto-line':           17,
  'goto-mark':           18,
  'goto-pos':            51,
  'help':                19,
  'index-file':          38,
  'invalid':             102,
  'left-scroll':         41,
  'mouse':               64,
  'mouse6':              68,
  'next-file':           20,
  'next-tag':            53,
  'no-scroll':           58,
  'noaction':            101,
  'osc8-forw-search':    71,
  'osc8-back-search':    72,
  'osc8-jump':           74,
  'osc8-open':           73,
  'percent':             21,
  'pipe':                37,
  'prev-file':           23,
  'prev-tag':            54,
  'pshell':              69,
  'quit':                24,
  'remove-file':         52,
  'repaint':             25,
  'repaint-flush':       11,
  'repeat-search':       43,
  'repeat-search-all':   44,
  'reverse-search':      45,
  'reverse-search-all':  46,
  'right-scroll':        42,
  'set-mark':            26,
  'set-mark-bottom':     63,
  'shell':               27,
  'status':              28,
  'toggle-flag':         47,
  'toggle-option':       47,
  'undo-hilite':         39,
  'version':             31,
  'visual':              32,
};

/** #line-edit action names, like less's editnames[]. */
export const EDIT_ACTION_CODES: Record<string, number> = {
  'back-complete':   18,
  'backspace':       1,
  'delete':          8,
  'down':            14,
  'end':             10,
  'expand':          15,
  'forw-complete':   17,
  'home':            9,
  'insert':          7,
  'invalid':         102,
  'kill-line':       2,
  'abort':           20,
  'left':            4,
  'literal':         19,
  'mouse':           21,
  'mouse6':          22,
  'noaction':        101,
  'right':           3,
  'up':              13,
  'word-backspace':  11,
  'word-delete':     12,
  'word-left':       5,
  'word-right':      6,
};

/**
 * A code back to ONE name, for rendering a binary as source.
 *
 * less lets several names share a code - "end" and "goto-end" are both
 * A_GOEND - so this keeps the first less lists, which is also the first
 * alphabetically. Any of them compiles back to the same byte.
 */
export const COMMAND_NAMES: Record<number, string> = {
  2:    'back-line',
  3:    'back-screen',
  4:    'back-scroll',
  5:    'back-search',
  6:    'digit',
  7:    'display-flag',
  8:    'debug',
  9:    'examine',
  10:   'first-cmd',
  11:   'flush-repaint',
  12:   'forw-line',
  13:   'forw-screen',
  14:   'forw-scroll',
  15:   'forw-search',
  16:   'end',
  17:   'goto-line',
  18:   'goto-mark',
  19:   'help',
  20:   'next-file',
  21:   'percent',
  22:   'back-screen-force',
  23:   'prev-file',
  24:   'quit',
  25:   'repaint',
  26:   'set-mark',
  27:   'shell',
  28:   'status',
  29:   'forw-line-force',
  30:   'back-line-force',
  31:   'version',
  32:   'visual',
  33:   'forw-window',
  34:   'back-window',
  35:   'forw-bracket',
  36:   'back-bracket',
  37:   'pipe',
  38:   'index-file',
  39:   'undo-hilite',
  40:   'forw-screen-force',
  41:   'left-scroll',
  42:   'right-scroll',
  43:   'repeat-search',
  44:   'repeat-search-all',
  45:   'reverse-search',
  46:   'reverse-search-all',
  47:   'toggle-flag',
  50:   'forw-forever',
  51:   'goto-pos',
  52:   'remove-file',
  53:   'next-tag',
  54:   'prev-tag',
  55:   'filter',
  56:   'forw-until-hilite',
  57:   'goto-end-buffered',
  58:   'no-scroll',
  59:   'end-scroll',
  60:   'forw-newline',
  61:   'back-newline',
  62:   'clear-mark',
  63:   'set-mark-bottom',
  64:   'mouse',
  68:   'mouse6',
  69:   'pshell',
  70:   'clear-search',
  71:   'osc8-forw-search',
  72:   'osc8-back-search',
  73:   'osc8-open',
  74:   'osc8-jump',
  77:   'forw-bell-hilite',
  101:  'noaction',
  102:  'invalid',
};

/** The same, for the #line-edit section. */
export const EDIT_ACTION_NAMES: Record<number, string> = {
  1:    'backspace',
  2:    'kill-line',
  3:    'right',
  4:    'left',
  5:    'word-left',
  6:    'word-right',
  7:    'insert',
  8:    'delete',
  9:    'home',
  10:   'end',
  11:   'word-backspace',
  12:   'word-delete',
  13:   'up',
  14:   'down',
  15:   'expand',
  17:   'forw-complete',
  18:   'back-complete',
  19:   'literal',
  20:   'abort',
  21:   'mouse',
  22:   'mouse6',
  101:  'noaction',
  102:  'invalid',
};

/**
 * SK_SPECIAL_KEY, the byte that opens a special-key blob in a compiled
 * file: CONTROL('K'). A literal ^K in a key sequence is stored as the
 * SK_CONTROL_K blob instead, so that this byte always means "blob".
 */
export const SK_SPECIAL_KEY = 0x0B;

/** SK_CONTROL_K: how a literal ^K is stored. */
export const SK_CONTROL_K = 40;

/**
 * Every \k form and the SK_* code it compiles to, out of less's tstr.
 *
 * A compiled file stores the blob `SK_SPECIAL_KEY <code> 6 1 1 1`, not
 * a terminal sequence - the reader expands it through terminfo when it
 * loads. Which is why this is a different table from the pager's own
 * \k handling, and a superset of it: the keypad forms have no
 * capability to resolve to, but they still compile.
 */
export const SPECIAL_KEY_CODES: Record<string, number> = {
  '+d':  43,
  '+e':  35,
  '+h':  34,
  '+l':  38,
  '+r':  39,
  '+u':  42,
  '+x':  46,
  '1':   14,
  'B':   16,
  'D':   6,
  'E':   37,
  'F':   35,
  'H':   36,
  'I':   34,
  'L':   11,
  'M':   38,
  'R':   12,
  'S':   39,
  'U':   5,
  'X':   13,
  '^b':  16,
  '^d':  45,
  '^e':  37,
  '^h':  36,
  '^l':  11,
  '^r':  12,
  '^u':  44,
  '^x':  13,
  'b':   17,
  'd':   4,
  'e':   8,
  'h':   7,
  'i':   10,
  'l':   2,
  'p*':  27,
  'p+':  30,
  'p,':  32,
  'p-':  29,
  'p.':  31,
  'p/':  28,
  'p0':  33,
  'p1':  25,
  'p2':  19,
  'p3':  24,
  'p4':  21,
  'p5':  26,
  'p6':  20,
  'p7':  23,
  'p8':  18,
  'p9':  22,
  'pe':  41,
  'r':   1,
  't':   15,
  'u':   3,
  'x':   9,
};

/**
 * less's built-in bindings, written out as lesskey source.
 *
 * --edit-lesskey opens this when a session has no lesskey of any kind,
 * so the editor holds what the keys ALREADY do rather than an empty
 * file - every binding is there to be changed or deleted, and the
 * shape of the syntax comes with it.
 *
 * It is less's own cmdtable/edittable (decode.c), not a description of
 * them: compile it and you get the defaults back. The two paste
 * markers appear commented out, because A_START_PASTE and A_END_PASTE
 * have no lesskey name to write.
 */
export const DEFAULT_KEYMAP: string[] = [
  '#command',
  '\\r\tforw-line',
  '\\n\tforw-line',
  'e\tforw-line',
  'j\tforw-line',
  '\\kd\tforw-line',
  '^E\tforw-line',
  '^N\tforw-line',
  'k\tback-line',
  'y\tback-line',
  '^Y\tback-line',
  '^K\tback-line',
  '^P\tback-line',
  '\\ku\tback-line',
  'J\tforw-line-force',
  'K\tback-line-force',
  'Y\tback-line-force',
  'd\tforw-scroll',
  '^D\tforw-scroll',
  'u\tback-scroll',
  '^U\tback-scroll',
  '\\e[M\tmouse',
  '\\e[<\tmouse6',
  '\\40\tforw-screen',
  'f\tforw-screen',
  '^F\tforw-screen',
  '^V\tforw-screen',
  '\\kD\tforw-screen',
  'b\tback-screen',
  '^B\tback-screen',
  '\\ev\tback-screen',
  '\\kU\tback-screen',
  'z\tforw-window',
  'w\tback-window',
  '\\e\\40\tforw-screen-force',
  '\\eb\tback-screen-force',
  '\\ej\tforw-newline',
  '\\ek\tback-newline',
  'F\tforw-forever',
  '\\ef\tforw-bell-hilite',
  '\\eF\tforw-until-hilite',
  'R\tflush-repaint',
  'r\trepaint',
  '^R\trepaint',
  '^L\trepaint',
  '\\eu\tundo-hilite',
  '\\eU\tclear-search',
  'g\tgoto-line',
  '\\kh\tgoto-line',
  '\\kI\tgoto-line\t\\e{',
  '\\kH\tgoto-line\t\\e{',
  '\\ke\tend',
  '\\kF\tend\t\\e}',
  '\\kE\tend\t\\e}',
  '<\tgoto-line',
  '\\e<\tgoto-line',
  'p\tpercent',
  '%\tpercent',
  '\\e(\tleft-scroll',
  '\\e)\tright-scroll',
  '\\e{\tno-scroll',
  '\\e}\tend-scroll',
  '\\kr\tright-scroll',
  '\\kl\tleft-scroll',
  '\\kR\tend-scroll',
  '\\kL\tno-scroll',
  '\\kS\tend-scroll',
  '\\kM\tno-scroll',
  '{\tforw-bracket\t{}',
  '}\tback-bracket\t{}',
  '(\tforw-bracket\t()',
  ')\tback-bracket\t()',
  '[\tforw-bracket\t[]',
  ']\tback-bracket\t[]',
  '\\e^F\tforw-bracket',
  '\\e^B\tback-bracket',
  'G\tend',
  '\\eG\tgoto-end-buffered',
  '\\e>\tend',
  '>\tend',
  'P\tgoto-pos',
  '0\tdigit',
  '1\tdigit',
  '2\tdigit',
  '3\tdigit',
  '4\tdigit',
  '5\tdigit',
  '6\tdigit',
  '7\tdigit',
  '8\tdigit',
  '9\tdigit',
  '.\tdigit',
  '=\tstatus',
  '^G\tstatus',
  ':f\tstatus',
  '/\tforw-search',
  '?\tback-search',
  '\\e/\tforw-search\t*',
  '\\e?\tback-search\t*',
  'n\trepeat-search',
  '\\en\trepeat-search-all',
  'N\treverse-search',
  '\\eN\treverse-search-all',
  '&\tfilter',
  'm\tset-mark',
  'M\tset-mark-bottom',
  '\\em\tclear-mark',
  '\\\'\tgoto-mark',
  '^X^X\tgoto-mark',
  'E\texamine',
  ':e\texamine',
  '^X^V\texamine',
  ':n\tnext-file',
  ':p\tprev-file',
  '^O^N\tosc8-forw-search',
  '^On\tosc8-forw-search',
  '^O^P\tosc8-back-search',
  '^Op\tosc8-back-search',
  '^O^O\tosc8-open',
  '^Oo\tosc8-open',
  '^O^L\tosc8-jump',
  '^Ol\tosc8-jump',
  't\tnext-tag',
  'T\tprev-tag',
  ':x\tindex-file',
  ':d\tremove-file',
  '-\ttoggle-flag',
  ':t\ttoggle-flag\tt',
  's\ttoggle-flag\to',
  '_\tdisplay-flag',
  '|\tpipe',
  'v\tvisual',
  '!\tshell',
  '\\#\tpshell',
  '+\tfirst-cmd',
  '\\kp8\tback-line',
  '\\kp2\tforw-line',
  '\\kp6\tright-scroll',
  '\\kp4\tleft-scroll',
  '\\kp9\tback-screen',
  '\\kp7\tgoto-line',
  '\\kp3\tforw-screen',
  '\\kp1\tend',
  '\\kp*\tnoaction\t*',
  '\\kp/\tnoaction\t/',
  '\\kp-\tnoaction\t-',
  '\\kp+\tnoaction\t+',
  '\\kp.\tnoaction\t.',
  '\\kp,\tnoaction',
  '\\kp0\tnoaction\t0',
  '\\kp5\tnoaction',
  '\\k^u\tnoaction',
  '\\k^d\tnoaction',
  '\\k+u\tnoaction',
  '\\k+d\tnoaction',
  '\\kx\tnoaction',
  '\\kX\tnoaction',
  '\\k+x\tnoaction',
  '\\ki\tnoaction',
  '\\kt\tnoaction',
  '\\kb\tnoaction',
  '\\kB\tnoaction',
  '\\b\tnoaction',
  '\\177\tnoaction',
  '# \\e[200~\t<A_START_PASTE: no lesskey name>',
  '# \\e[201~\t<A_END_PASTE: no lesskey name>',
  'H\thelp',
  'h\thelp',
  '\\k1\thelp',
  'V\tversion',
  'q\tquit',
  'Q\tquit',
  ':q\tquit',
  ':Q\tquit',
  'ZZ\tquit',
  '',
  '#line-edit',
  '\\t\tforw-complete',
  '\\017\tback-complete',
  '\\kt\tback-complete',
  '\\e\\t\tback-complete',
  '^L\texpand',
  '^V\tliteral',
  '^A\tliteral',
  '\\el\tright',
  '\\kr\tright',
  '\\eh\tleft',
  '\\kl\tleft',
  '\\eb\tword-left',
  '\\e\\kl\tword-left',
  '\\kL\tword-left',
  '\\ew\tword-right',
  '\\e\\kr\tword-right',
  '\\kR\tword-right',
  '\\ei\tinsert',
  '\\ki\tinsert',
  '\\ex\tdelete',
  '\\kx\tdelete',
  '\\eX\tword-delete',
  '\\e\\kx\tword-delete',
  '\\kX\tword-delete',
  '\\kB\tword-backspace',
  '\\e\\kb\tword-backspace',
  '\\e0\thome',
  '\\kh\thome',
  '\\kI\thome',
  '\\kH\thome',
  '\\e$\tend',
  '\\ke\tend',
  '\\kF\tend',
  '\\kE\tend',
  '\\ek\tup',
  '\\ku\tup',
  '\\ej\tdown',
  '\\kd\tdown',
  '^G\tabort',
  '\\kp8\tup',
  '\\kp2\tdown',
  '\\kp6\tright',
  '\\kp4\tleft',
  '\\kp9\tnoaction',
  '\\kp7\thome',
  '\\kp3\tnoaction',
  '\\kp1\tend',
  '\\kp*\tnoaction\t*',
  '\\kp/\tnoaction\t/',
  '\\kp-\tnoaction\t-',
  '\\kp+\tnoaction\t+',
  '\\kp.\tnoaction\t.',
  '\\kp,\tnoaction',
  '\\kp0\tnoaction\t0',
  '\\kp5\tnoaction',
  '\\k^u\tnoaction',
  '\\k^d\tnoaction',
  '\\k+u\tnoaction',
  '\\k+d\tnoaction',
  '\\k+x\tnoaction',
  '\\kU\tnoaction',
  '\\kD\tnoaction',
  '\\kM\tnoaction',
  '\\kS\tnoaction',
  '\\e[M\tmouse',
  '\\e[<\tmouse6',
  '# \\e[200~\t<A_START_PASTE: no lesskey name>',
  '# \\e[201~\t<A_END_PASTE: no lesskey name>',
];
