/* v8 ignore start */
/* eslint-disable max-len */

/**
 * The lesskey syntax page, shown by --lesskey-help.
 *
 * NOT an og screen: og documents lesskey in a man page that ships with
 * the less distribution, which an npm install of this pager does not
 * bring with it. Same rendering as the command help - overstrike
 * sequences (X\bX bold, _\bX underline) through the normal content
 * pipeline - and paged the same way, as its own input file.
 *
 * Started as a copy of lessHelp.ts; the body is being rewritten.
 */
export const lesskeyHelp: string[] = [
  "",
  "                     S\bSY\bYN\bNT\bTA\bAX\bX O\bOF\bF L\bLE\bES\bSS\bSK\bKE\bEY\bY",
  "",
  "      _\bO_\bP means operator; _\bN means number.",
  "      Blank lines and text after an unescaped # are ignored.",
  "",
  "  #command  #line-edit  #env    Start a section.",
  "  #stop                         Discard all built-in bindings.",
  "        ---------------------------------------------------",
  "        WARNING: #stop without a quit binding leads to frustration!",
  "",
  "  #version _\bO_\bP _\bN                 Use the rest of the line if less versions match.",
  "        ---------------------------------------------------",
  "        #version operators:",
  "            >    Greater than",
  "            >=   Greater than or equal to",
  "            <    Less than",
  "            <=   Less than or equal to",
  "            =    Equal to",
  "            !=   Not equal to",
  "",
  "  _\bE_\bN_\bV  = _\bv_\ba_\bl_\bu_\be                  Assign a _\bv_\ba_\bl_\bu_\be to _\bE_\bN_\bV.",
  "  _\bE_\bN_\bV += _\bv_\ba_\bl_\bu_\be                  Append to the _\bE_\bN_\bV assigned right above.",
  "        ---------------------------------------------------",
  "        Lesskey variables take precedence over the real environment.",
  "        Whitespace around = and += is ignored.",
  " ---------------------------------------------------------------------------",
  "",
  "                        D\bDE\bEF\bFI\bIN\bNI\bIT\bTI\bIO\bON\bNS\bS",
  "",
  "  #\b#s\bse\bec\bct\bti\bio\bon\bn                   Start of a section.",
  "  _\bs_\be_\bq_\bu_\be_\bn_\bc_\be  _\ba_\bc_\bt_\bi_\bo_\bn           Bind a key sequence to an action.",
  "  _\bs_\be_\bq_\bu_\be_\bn_\bc_\be  _\ba_\bc_\bt_\bi_\bo_\bn  _\be_\bx_\bt_\br_\ba    Bind, then type _\be_\bx_\bt_\br_\ba after _\ba_\bc_\bt_\bi_\bo_\bn.",
  "        ---------------------------------------------------",
  "        A _\bs_\be_\bq_\bu_\be_\bn_\bc_\be is 1 to 15 command keys, pressed in order.",
  " ---------------------------------------------------------------------------",
  "",
  "                        K\bKE\bEY\bY N\bNO\bOT\bTA\bAT\bTI\bIO\bON\bN",
  "",
  "  \\k1    F1",
  "  \\e     ESCAPE",
  "  \\ki    INSERT",
  "  \\t     TAB             \\kt    BACKTAB",
  "  \\r     RETURN          \\n     NEWLINE",
  "  \\kx    DELETE          \\kX    ctrl-DELETE          \\k+x   shift-DELETE",
  "  \\b     0x08            \\kb    BACKSPACE            \\kB    ctrl-BACKSPACE",
  "  \\kU    PAGE UP         \\kD    PAGE DOWN",
  "  \\kh    HOME            \\kH    ctrl-HOME            \\kI    shift-HOME",
  "  \\ke    END             \\kE    ctrl-END             \\kF    shift-END",
  "  \\ku    UpArrow         \\k^u   ctrl-UpArrow         \\k+u   shift-UpArrow",
  "  \\kd    DownArrow       \\k^d   ctrl-DownArrow       \\k+d   shift-DownArrow",
  "  \\kl    LeftArrow       \\kL    ctrl-LeftArrow       \\kM    shift-LeftArrow",
  "  \\kr    RightArrow      \\kR    ctrl-RightArrow      \\kS    shift-RightArrow",
  "        ---------------------------------------------------",
  "        ^_\bX               Control key; so ^K is ctrl-K.",
  "        \\_\bN_\bN_\bN             1 to 3 octal digits (0-7).",
  "        \\40    \"\\ \"      Literal space.",
  "        \\\\  \\^  \\#       Literal backslash, caret and hash.",
  "        Numeric keypad:",
  "            \\kp1    lower left key",
  "            \\kp2    lower center key",
  "            \\kp3    lower right key",
  "            \\kp4    center left key",
  "            \\kp5    center key",
  "            \\kp6    center right key",
  "            \\kp7    upper left key",
  "            \\kp8    upper center key",
  "            \\kp9    upper right key",
  "            \\kp0    0           \\kp*    *",
  "            \\kp/    /           \\kp-    -",
  "            \\kp+    +           \\kp.    .",
  "            \\kp,    ,           \\kpe    ENTER",
  " ---------------------------------------------------------------------------",
  "",
  "                          A\bAC\bCT\bTI\bIO\bON\bNS\bS",
  "",
  "  #\b#c\bco\bom\bmm\bma\ban\bnd\bd",
  "  forw-line            Forward  one line   (or _\bN lines).",
  "  back-line            Backward one line   (or _\bN lines).",
  "  forw-line-force      Forward  one line, but don't stop at end-of-file.",
  "  back-line-force      Backward one line, but don't stop at beginning-of-file.",
  "  forw-scroll          Forward  one half-window (and set half-window to _\bN).",
  "  back-scroll          Backward one half-window (and set half-window to _\bN).",
  "  forw-screen          Forward  one window (or _\bN lines).",
  "  back-screen          Backward one window (or _\bN lines).",
  "  forw-window          Forward  one window (and set window to _\bN).",
  "  back-window          Backward one window (and set window to _\bN).",
  "  forw-screen-force    Forward  one window, but don't stop at end-of-file.",
  "  back-screen-force    Backward one window, but don't stop at beginning-of-file.",
  "  forw-newline         Forward  one file line (or _\bN file lines).",
  "  back-newline         Backward one file line (or _\bN file lines).",
  "  forw-forever         Forward forever; like \"tail -f\".",
  "  forw-until-hilite    Like F but stop when search pattern is found.",
  "  forw-bell-hilite     Like F but ring the bell when search pattern is found.",
  "  repaint-flush        Repaint screen, discarding buffered input.",
  "  flush-repaint        Repaint screen, discarding buffered input.",
  "  repaint              Repaint screen.",
  "  undo-hilite          Undo (toggle) search highlighting.",
  "  clear-search         Clear search highlighting.",
  "  goto-line            Go to first line in file (or line _\bN).",
  "  goto-end             Go to last line in file (or line _\bN).",
  "  end                  Go to last line in file (or line _\bN).",
  "  percent              Go to beginning of file (or _\bN percent into file).",
  "  left-scroll          Left  one half screen width (or _\bN positions).",
  "  right-scroll         Right one half screen width (or _\bN positions).",
  "  no-scroll            Left  to first column.",
  "  end-scroll           Right to last column displayed.",
  "  forw-bracket         Find close bracket _\b<_\bc_\b2_\b>.",
  "  back-bracket         Find open bracket _\b<_\bc_\b1_\b>.",
  "  goto-pos             Go to byte position _\bN in the file.",
  "  goto-end-buffered    Go to last buffered byte (or line _\bN).",
  "  status               Print current file name.",
  "  forw-search          Search forward for (_\bN-th) matching line.",
  "  back-search          Search backward for (_\bN-th) matching line.",
  "  repeat-search        Repeat previous search (for _\bN-th occurrence).",
  "  repeat-search-all    Repeat previous search, spanning files.",
  "  reverse-search       Repeat previous search in reverse direction.",
  "  reverse-search-all   Repeat previous search, reverse dir. & spanning files.",
  "  filter               Display only matching lines.",
  "  set-mark             Mark the top line (or line _\bN) with <letter>.",
  "  set-mark-bottom      Mark the bottom line (or line _\bN) with <letter>.",
  "  clear-mark           Clear a mark.",
  "  goto-mark            Go to a previously marked position.",
  "  examine              Examine a new file.",
  "  next-file            Examine the (_\bN-th) next file from the command line.",
  "  prev-file            Examine the (_\bN-th) previous file from the command line.",
  "  osc8-forw-search     Search forward for (_\bN-th) OSC8 hyperlink.",
  "  osc8-back-search     Search backward for (_\bN-th) OSC8 hyperlink.",
  "  osc8-open            Open the currently selected OSC8 hyperlink.",
  "  osc8-jump            Jump to the currently selected OSC8 hyperlink.",
  "  next-tag             Go to the (_\bN-th) next tag.",
  "  prev-tag             Go to the (_\bN-th) previous tag.",
  "  index-file           Examine the first (or _\bN-th) file from the command line.",
  "  remove-file          Delete the current file from the command line list.",
  "  toggle-option        Toggle a command line option.",
  "  toggle-flag          Toggle a command line option.",
  "  display-option       Display the setting of a command line option.",
  "  display-flag         Display the setting of a command line option.",
  "  pipe                 Pipe file between current pos & mark _\b<_\bl_\be_\bt_\bt_\be_\br_\b> to shell.",
  "  visual               Edit the current file with $VISUAL or $EDITOR.",
  "  shell                Execute the shell command with $SHELL.",
  "  pshell               Execute the shell command, expanded like a prompt.",
  "  firstcmd             Execute the less cmd each time a new file is examined.",
  "  first-cmd            Execute the less cmd each time a new file is examined.",
  "  mouse                Start of an X10/X11 mouse report.",
  "  mouse6               Start of an SGR (1006) mouse report.",
  "  noaction             Disable the key, silently.",
  "  help                 Display this help.",
  "  version              Print version number of \"less-pager-mini\".",
  "  digit                Add a digit to the number before a command.",
  "  quit                 Exit.",
  "  debug                Disable the key, with a bell; no command exists.",
  "  invalid              Disable the key, with a bell.",
  "",
  "  #\b#l\bli\bin\bne\be-\b-e\bed\bdi\bit\bt",
  "  forw-complete        Complete filename & cycle.",
  "  back-complete        Complete filename & reverse cycle.",
  "  expand               Complete filename, list all.",
  "  literal              Enter the next character literally.",
  "  right                Move cursor right one character.",
  "  left                 Move cursor left one character.",
  "  word-left            Move cursor left one word.",
  "  word-right           Move cursor right one word.",
  "  insert               Toggle insert mode.",
  "  delete               Delete char under cursor.",
  "  word-delete          Delete word under cursor.",
  "  word-backspace       Delete word to left of cursor.",
  "  home                 Move cursor to start of line.",
  "  end                  Move cursor to end of line.",
  "  up                   Retrieve previous command line.",
  "  down                 Retrieve next command line.",
  "  abort                Cancel the command line.",
  "  noaction             Disable the key, silently.",
  "  mouse                Start of an X10/X11 mouse report.",
  "  mouse6               Start of an SGR (1006) mouse report.",
  "  backspace            Delete char to left of cursor.",
  "  invalid              Disable the key, with a bell.",
  "  kill-line            Delete entire line.",
  "",
  " ---------------------------------------------------------------------------",
  "",
  "                   E\bEN\bNV\bVI\bIR\bRO\bON\bNM\bME\bEN\bNT\bT V\bVA\bAR\bRI\bIA\bAB\bBL\bLE\bES\bS",
  "",
  "  #\b#e\ben\bnv\bv",
  "  COLUMNS                   Number of columns on the screen.",
  "  EDITOR                    The editor used for the v command.",
  "  HOME                      The user's home directory; where a lesskey is found.",
  "  HOMEDRIVE                 With HOMEPATH, the home directory on Windows.",
  "  HOMEPATH                  With HOMEDRIVE, the home directory on Windows.",
  "  LANG                      Language, for determining the character set.",
  "  LC_ALL                    Language, for determining the character set.",
  "  LC_CTYPE                  Language, for determining the character set.",
  "  LESS                      Options passed to less automatically.",
  "  LESSANSIENDCHARS          Characters which may end an ANSI escape sequence.",
  "  LESSANSIMIDCHARS          Characters which may appear inside one.",
  "  LESSANSIOSCALLOW          OSC types output directly to the terminal.",
  "  LESSANSIOSCCHARS          Characters which may start an OS Command sequence.",
  "  LESSBINFMT                Format for non-printable, non-control characters.",
  "  LESSCHARDEF               Defines a character set.",
  "  LESSCHARSET               Selects a predefined character set.",
  "  LESSCLOSE                 Command line to invoke the input-postprocessor.",
  "  LESSECHO                  Name of the lessecho program.",
  "  LESSEDIT                  Editor prototype string, used for the v command.",
  "  LESSGLOBALTAGS            Command used by -t to find global tags.",
  "  LESSHISTFILE              History file for search and shell commands.",
  "  LESSHISTSIZE              How many commands to save in the history file.",
  "  LESSKEY                   Name of the default lesskey file.",
  "  LESSKEYIN                 Name of the default lesskey source file.",
  "  LESSKEYIN_SYSTEM          Name of the system-wide lesskey source file.",
  "  LESSKEY_CONTENT           Parsed as if it were a lesskey source file.",
  "  LESSKEY_CONTENT_SYSTEM    The same, system-wide.",
  "  LESSKEY_SYSTEM            Name of the system-wide lesskey file.",
  "  LESSMETACHARS             Characters the shell treats as metacharacters.",
  "  LESSMETAESCAPE            Prefix added before each metacharacter.",
  "  LESSOPEN                  Command line to invoke the input-preprocessor.",
  "  LESSSECURE                Run in secure mode.",
  "  LESSSECURE_ALLOW          Re-enable features LESSSECURE disables.",
  "  LESSSECURE_DISALLOW       Disable features when LESSSECURE is unset.",
  "  LESSSEPARATOR             Appended to a directory name in completion.",
  "  LESSUTFBINFMT             Format for non-printable Unicode code points.",
  "  LESSUTFCHARDEF            Overrides the type of Unicode characters.",
  "  LESS_COLUMNS              Columns to use; beats the system screen size.",
  "  LESS_DATA_DELAY           Milliseconds before \"Waiting for data\" shows.",
  "  LESS_IS_MORE              Emulate the more command.",
  "  LESS_LINES                Lines to use; beats the system screen size.",
  "  LESS_OSC8_OPEN__\b<_\bs_\bc_\bh_\be_\bm_\be_\b>   OSC 8 handler for that URI scheme.",
  "  LESS_OSC8_OPEN_ANY        OSC 8 handler for schemes with no handler.",
  "  LESS_SCREENFILL_TIME      Milliseconds to wait for the first screenful.",
  "  LESS_SHELL_COPTION        Option that passes a command to $SHELL.",
  "  LESS_SHELL_LINES          Lines reserved for shell output under -F.",
  "  LESS_SIGUSR1              Commands to run when less receives SIGUSR1.",
  "  LESS_TERMCAP__\b<_\bc_\ba_\bp_\b>        Override that 2-char termcap capability.",
  "  LESS_TERMCAP_DEBUG        Show each capability name instead of its value.",
  "  LESS_TERMINFO__\b<_\bc_\ba_\bp_\b>       Override that terminfo capability.",
  "  LESS_UNSUPPORT            Options to ignore without an error message.",
  "  LINES                     Number of lines on the screen.",
  "  MORE                      Options passed automatically when run as more.",
  "  SHELL                     The shell used by ! and for expanding filenames.",
  "  TERM                      The type of terminal less is running on.",
  "  TERMCAP                   The terminal description database.",
  "  VISUAL                    The editor used for the v command.",
  "  XDG_CONFIG_HOME           Possible location of the lesskey file.",
  "  XDG_DATA_HOME             Possible location of the history file.",
  "  XDG_STATE_HOME            Possible location of the history file.",
  " ---------------------------------------------------------------------------",
  "",
  "                          E\bEX\bXA\bAM\bMP\bPL\bLE\bE",
  "",
  "      #\b#c\bco\bom\bmm\bma\ban\bnd\bd",
  "      ZZ            quit",
  "      \\kd           forw-line",
  "      ^G            repaint",
  "      X             noaction",
  "      \\e[15~        forw-search    ERROR\\n",
  "",
  "      #\b#l\bli\bin\bne\be-\b-e\bed\bdi\bit\bt",
  "      \\kx           delete",
  "",
  "      #\b#e\ben\bnv\bv",
  "      LESS = -R",
  "      LESS += \\ --use-color",
  " ---------------------------------------------------------------------------",
  "",
  "        This help is adapted from the \"lesskey\" man page by Mark Nudelman.",
  "        Original: http://greenwoodsoftware.com/less/"
];
