/* v8 ignore start */
/* eslint-disable max-len */

/**
 * The help page, generated from og's less.hlp (707x): overstrike
 * sequences (X\bX bold, _\bX underline) render through the normal
 * content pipeline, like og paging its own help file.
 */
export const help: string[] = [
  "",
  "                   S\bSU\bUM\bMM\bMA\bAR\bRY\bY O\bOF\bF L\bLE\bES\bSS\bS C\bCO\bOM\bMM\bMA\bAN\bND\bDS\bS",
  "",
  "      Commands marked with * may be preceded by a number, _\bN.",
  "      Notes in parentheses indicate the behavior if _\bN is given.",
  "      A key preceded by a caret indicates the Ctrl key; thus ^K is ctrl-K.",
  "",
  "  h  H                 Display this help.",
  "  q  :q  Q  :Q  ZZ     Exit.",
  " ---------------------------------------------------------------------------",
  "",
  "                           M\bMO\bOV\bVI\bIN\bNG\bG",
  "",
  "  e  ^E  j  ^N  CR  *  Forward  one line   (or _\bN lines).",
  "  y  ^Y  k  ^K  ^P  *  Backward one line   (or _\bN lines).",
  "  J                 *  Forward  one line, but don't stop at end-of-file.",
  "  K  Y              *  Backward one line, but don't stop at beginning-of-file.",
  "  ESC-j             *  Forward  one file line (or _\bN file lines).",
  "  ESC-k             *  Backward one file line (or _\bN file lines).",
  "  f  ^F  ^V  SPACE  *  Forward  one window (or _\bN lines).",
  "  b  ^B  ESC-v      *  Backward one window (or _\bN lines).",
  "  z                 *  Forward  one window (and set window to _\bN).",
  "  w                 *  Backward one window (and set window to _\bN).",
  "  ESC-SPACE         *  Forward  one window, but don't stop at end-of-file.",
  "  ESC-b             *  Backward one window, but don't stop at beginning-of-file.",
  "  d  ^D             *  Forward  one half-window (and set half-window to _\bN).",
  "  u  ^U             *  Backward one half-window (and set half-window to _\bN).",
  "  ESC-)  RightArrow *  Right one half screen width (or _\bN positions).",
  "  ESC-(  LeftArrow  *  Left  one half screen width (or _\bN positions).",
  "  ESC-}  ^RightArrow   Right to last column displayed.",
  "  ESC-{  ^LeftArrow    Left  to first column.",
  "  F                    Forward forever; like \"tail -f\".",
  "  ESC-F                Like F but stop when search pattern is found.",
  "  ESC-f                Like F but ring the bell when search pattern is found.",
  "  r  ^R  ^L            Repaint screen.",
  "  R                    Repaint screen, discarding buffered input.",
  "        ---------------------------------------------------",
  "        Default \"window\" is the screen height.",
  "        Default \"half-window\" is half of the screen height.",
  " ---------------------------------------------------------------------------",
  "",
  "                          S\bSE\bEA\bAR\bRC\bCH\bHI\bIN\bNG\bG",
  "",
  "  /_\bp_\ba_\bt_\bt_\be_\br_\bn          *  Search forward for (_\bN-th) matching line.",
  "  ?_\bp_\ba_\bt_\bt_\be_\br_\bn          *  Search backward for (_\bN-th) matching line.",
  "  n                 *  Repeat previous search (for _\bN-th occurrence).",
  "  N                 *  Repeat previous search in reverse direction.",
  "  ESC-n             *  Repeat previous search, spanning files.",
  "  ESC-N             *  Repeat previous search, reverse dir. & spanning files.",
  "  ^O^N  ^On         *  Search forward for (_\bN-th) OSC8 hyperlink.",
  "  ^O^P  ^Op         *  Search backward for (_\bN-th) OSC8 hyperlink.",
  "  ^O^L  ^Ol            Jump to the currently selected OSC8 hyperlink.",
  "  ESC-u                Undo (toggle) search highlighting.",
  "  ESC-U                Clear search highlighting.",
  "  &_\bp_\ba_\bt_\bt_\be_\br_\bn          *  Display only matching lines.",
  "        ---------------------------------------------------",
  "        Search is case-sensitive unless changed with -i or -I.",
  "        A search pattern may begin with one or more of:",
  "        ^N or !  Search for NON-matching lines.",
  "        ^E or *  Search multiple files (pass thru END OF FILE).",
  "        ^F or @  Start search at FIRST file (for /) or last file (for ?).",
  "        ^K       Highlight matches, but don't move (KEEP position).",
  "        ^R       Don't use REGULAR EXPRESSIONS.",
  "        ^S _\bn     Search for match in _\bn-th parenthesized subpattern.",
  "        ^W       WRAP search if no match found.",
  "        ^L       Enter next character literally into pattern.",
  " ---------------------------------------------------------------------------",
  "",
  "                           J\bJU\bUM\bMP\bPI\bIN\bNG\bG",
  "",
  "  g  <  ESC-<  HOME *  Go to first line in file (or line _\bN).",
  "  G  >  ESC->  END  *  Go to last line in file (or line _\bN).",
  "  p  %              *  Go to beginning of file (or _\bN percent into file).",
  "  t                 *  Go to the (_\bN-th) next tag.",
  "  T                 *  Go to the (_\bN-th) previous tag.",
  "  {  (  [           *  Find close bracket } ) ].",
  "  }  )  ]           *  Find open bracket { ( [.",
  "  ESC-^F _\b<_\bc_\b1_\b> _\b<_\bc_\b2_\b>  *  Find close bracket _\b<_\bc_\b2_\b>.",
  "  ESC-^B _\b<_\bc_\b1_\b> _\b<_\bc_\b2_\b>  *  Find open bracket _\b<_\bc_\b1_\b>.",
  "        ---------------------------------------------------",
  "        Each \"find close bracket\" command goes forward to the close bracket ",
  "          matching the (_\bN-th) open bracket in the top line.",
  "        Each \"find open bracket\" command goes backward to the open bracket ",
  "          matching the (_\bN-th) close bracket in the bottom line.",
  "",
  "  m_\b<_\bl_\be_\bt_\bt_\be_\br_\b>         *  Mark the top line (or line _\bN) with <letter>.",
  "  M_\b<_\bl_\be_\bt_\bt_\be_\br_\b>         *  Mark the bottom line (or line _\bN) with <letter>.",
  "  '_\b<_\bl_\be_\bt_\bt_\be_\br_\b>         *  Go to a previously marked position (put on position _\bN).",
  "  ''                *  Go to the previous position.",
  "  ^X^X              *  Same as '.",
  "  ESC-m_\b<_\bl_\be_\bt_\bt_\be_\br_\b>        Clear a mark.",
  "        ---------------------------------------------------",
  "        A mark is any upper-case or lower-case letter.",
  "        Certain marks are predefined:",
  "             ^  means  beginning of the file",
  "             $  means  end of the file",
  " ---------------------------------------------------------------------------",
  "",
  "                        C\bCH\bHA\bAN\bNG\bGI\bIN\bNG\bG F\bFI\bIL\bLE\bES\bS",
  "",
  "  :e [_\bf_\bi_\bl_\be]            Examine a new file.",
  "  ^X^V                 Same as :e.",
  "  :n                *  Examine the (_\bN-th) next file from the command line.",
  "  :p                *  Examine the (_\bN-th) previous file from the command line.",
  "  :x                *  Examine the first (or _\bN-th) file from the command line.",
  "  ^O^O                 Open the currently selected OSC8 hyperlink.",
  "  :d                   Delete the current file from the command line list.",
  "  =  ^G  :f            Print current file name.",
  " ---------------------------------------------------------------------------",
  "",
  "                    M\bMI\bIS\bSC\bCE\bEL\bLL\bLA\bAN\bNE\bEO\bOU\bUS\bS C\bCO\bOM\bMM\bMA\bAN\bND\bDS\bS",
  "",
  "  -_\b<_\bf_\bl_\ba_\bg_\b>              Toggle a command line option [see OPTIONS below].",
  "  --_\b<_\bn_\ba_\bm_\be_\b>             Toggle a command line option, by name.",
  "  __\b<_\bf_\bl_\ba_\bg_\b>              Display the setting of a command line option.",
  "  ___\b<_\bn_\ba_\bm_\be_\b>             Display the setting of an option, by name.",
  "  +_\bc_\bm_\bd                 Execute the less cmd each time a new file is examined.",
  "",
  "  !_\bc_\bo_\bm_\bm_\ba_\bn_\bd             Execute the shell command with $SHELL.",
  "  #_\bc_\bo_\bm_\bm_\ba_\bn_\bd             Execute the shell command, expanded like a prompt.",
  "  |X\bX_\bc_\bo_\bm_\bm_\ba_\bn_\bd            Pipe file between current pos & mark X\bX to shell command.",
  "  s _\bf_\bi_\bl_\be               Save input to a file.",
  "  v                    Edit the current file with $VISUAL or $EDITOR.",
  "  V                    Print version number of \"less-pager-mini\".",
  " ---------------------------------------------------------------------------",
  "",
  "                           O\bOP\bPT\bTI\bIO\bON\bNS\bS",
  "",
  "        Most options may be changed either on the command line,",
  "        or from within less by using the - or -- command.",
  "        Options may be given in one of two forms: either a single",
  "        character preceded by a -, or a name preceded by --.",
  "",
  "  -?  ........  --help",
  "                  Display help (from command line).",
  "  -a  ........  --search-skip-screen",
  "                  Search skips current screen.",
  "  -A  ........  --SEARCH-SKIP-SCREEN",
  "                  Search starts just after target line.",
  "  -b [_\bN]  ....  --buffers=[_\bN]",
  "                  Number of buffers.",
  "  -B  ........  --auto-buffers",
  "                  Don't automatically allocate buffers for pipes.",
  "  -c  ........  --clear-screen",
  "                  Repaint by clearing rather than scrolling.",
  "  -d  ........  --dumb",
  "                  Dumb terminal.",
  "  -D x\bx_\bc_\bo_\bl_\bo_\br  .  --color=x\bx_\bc_\bo_\bl_\bo_\br",
  "                  Set screen colors.",
  "  -e  -E  ....  --quit-at-eof  --QUIT-AT-EOF",
  "                  Quit at end of file.",
  "  -f  ........  --force",
  "                  Force open non-regular files.",
  "  -F  ........  --quit-if-one-screen",
  "                  Quit if entire file fits on first screen.",
  "  -g  ........  --hilite-search",
  "                  Highlight only last match for searches.",
  "  -G  ........  --HILITE-SEARCH",
  "                  Don't highlight any matches for searches.",
  "  -h [_\bN]  ....  --max-back-scroll=[_\bN]",
  "                  Backward scroll limit.",
  "  -i  ........  --ignore-case",
  "                  Ignore case in searches that do not contain uppercase.",
  "  -I  ........  --IGNORE-CASE",
  "                  Ignore case in all searches.",
  "  -j [_\bN]  ....  --jump-target=[_\bN]",
  "                  Screen position of target lines.",
  "  -J  ........  --status-column",
  "                  Display a status column at left edge of screen.",
  "  -k _\bf_\bi_\bl_\be  ...  --lesskey-file=_\bf_\bi_\bl_\be",
  "                  Use a compiled lesskey file.",
  "  -K  ........  --quit-on-intr",
  "                  Exit less in response to ctrl-C.",
  "  -L  ........  --no-lessopen",
  "                  Ignore the LESSOPEN environment variable.",
  "  -m  -M  ....  --long-prompt  --LONG-PROMPT",
  "                  Set prompt style.",
  "  -n .........  --line-numbers",
  "                  Suppress line numbers in prompts and messages.",
  "  -N .........  --LINE-NUMBERS",
  "                  Display line number at start of each line.",
  "  -o [_\bf_\bi_\bl_\be] ..  --log-file=[_\bf_\bi_\bl_\be]",
  "                  Copy to log file (standard input only).",
  "  -O [_\bf_\bi_\bl_\be] ..  --LOG-FILE=[_\bf_\bi_\bl_\be]",
  "                  Copy to log file (unconditionally overwrite).",
  "  -p _\bp_\ba_\bt_\bt_\be_\br_\bn .  --pattern=[_\bp_\ba_\bt_\bt_\be_\br_\bn]",
  "                  Start at pattern (from command line).",
  "  -P [_\bp_\br_\bo_\bm_\bp_\bt]   --prompt=[_\bp_\br_\bo_\bm_\bp_\bt]",
  "                  Define new prompt.",
  "  -q  -Q  ....  --quiet  --QUIET  --silent --SILENT",
  "                  Quiet the terminal bell.",
  "  -r  -R  ....  --raw-control-chars  --RAW-CONTROL-CHARS",
  "                  Output \"raw\" control characters.",
  "  -s  ........  --squeeze-blank-lines",
  "                  Squeeze multiple blank lines.",
  "  -S  ........  --chop-long-lines",
  "                  Chop (truncate) long lines rather than wrapping.",
  "  -t _\bt_\ba_\bg  ....  --tag=[_\bt_\ba_\bg]",
  "                  Find a tag.",
  "  -T [_\bt_\ba_\bg_\bs_\bf_\bi_\bl_\be] --tag-file=[_\bt_\ba_\bg_\bs_\bf_\bi_\bl_\be]",
  "                  Use an alternate tags file.",
  "  -u  -U  ....  --underline-special  --UNDERLINE-SPECIAL",
  "                  Change handling of backspaces, tabs and carriage returns.",
  "  -V  ........  --version",
  "                  Display the version number of \"less-pager-mini\".",
  "  -w  ........  --hilite-unread",
  "                  Highlight first new line after full screen movement.",
  "  -W  ........  --HILITE-UNREAD",
  "                  Highlight first new line after any movement.",
  "  -x [_\bN[,...]]  --tabs=[_\bN[,...]]",
  "                  Set tab stops.",
  "  -X  ........  --no-init",
  "                  Don't use termcap init/deinit strings.",
  "  -y [_\bN]  ....  --max-forw-scroll=[_\bN]",
  "                  Forward scroll limit.",
  "  -z [_\bN]  ....  --window=[_\bN]",
  "                  Set size of window.",
  "  -\" [_\bc[_\bc]]  .  --quotes=[_\bc[_\bc]]",
  "                  Set shell quote characters.",
  "  -~  ........  --tilde",
  "                  Don't display tildes after end of file.",
  "  -# [_\bN]  ....  --shift=[_\bN]",
  "                  Set horizontal scroll amount (0 = one half screen width).",
  "",
  "                --autosave=[_\bm_\b/_\b!_\b*]",
  "                  Actions which cause the history file to be saved.",
  "                --emouse=[_\bv_\bs_\bc_\br_\bo_\bl_\bl,_\bv_\bd_\br_\ba_\bg,_\bh_\bs_\bc_\br_\bo_\bl_\bl,_\bh_\bd_\br_\ba_\bg,_\bl_\bc_\bl_\bi_\bc_\bk,_\br_\bc_\bl_\bi_\bc_\bk]",
  "                  Enable mouse features.",
  "                --end-prompt=[_\bs_\bt_\br_\bi_\bn_\bg]",
  "                  String to be printed after erasing the prompt.",
  "                --exit-follow-on-close",
  "                  Exit F command on a pipe when writer closes pipe.",
  "                --file-size",
  "                  Automatically determine the size of the input file.",
  "                --follow-name",
  "                  The F command changes files if the input file is renamed.",
  "                --form-feed",
  "                  Stop scrolling when a form feed character is reached.",
  "                --header=[_\bL[,_\bC[,_\bN]]]",
  "                  Use _\bL lines (starting at line _\bN) and _\bC columns as headers.",
  "                --hilite-target",
  "                  Highlight the target line.",
  "                --incsearch",
  "                  Search file as each pattern character is typed in.",
  "                --intr=[_\bC]",
  "                  Use _\bC instead of ^X to interrupt a read.",
  "                --lesskey-context=_\bt_\be_\bx_\bt",
  "                  Use lesskey source file contents.",
  "                --lesskey-src=_\bf_\bi_\bl_\be",
  "                  Use a lesskey source file.",
  "                --line-num-width=[_\bN]",
  "                  Set the width of the -N line number field to _\bN characters.",
  "                --match-shift=[_\bN]",
  "                  Show at least _\bN characters to the left of a search match.",
  "                --modelines=[_\bN]",
  "                  Read _\bN lines from the input file and look for vim modelines.",
  "                --mouse",
  "                  Enable mouse clicking and vertical scrolling.",
  "                --no-edit-warn",
  "                  Don't warn when using v command on a file opened via LESSOPEN.",
  "                --no-keypad",
  "                  Don't send termcap keypad init/deinit strings.",
  "                --no-histdups",
  "                  Remove duplicates from command history.",
  "                --no-number-headers",
  "                  Don't give line numbers to header lines.",
  "                --no-paste",
  "                  Ignore pasted input.",
  "                --no-search-header-lines",
  "                  Searches do not include header lines.",
  "                --no-search-header-columns",
  "                  Searches do not include header columns.",
  "                --no-search-headers",
  "                  Searches do not include header lines or columns.",
  "                --no-vbell",
  "                  Disable the terminal's visual bell.",
  "                --redraw-on-quit",
  "                  Redraw final screen when quitting.",
  "                --rscroll=[_\bC]",
  "                  Set the character used to mark truncated lines.",
  "                --save-marks",
  "                  Retain marks across invocations of less.",
  "                --search-options=[EFKNRW-]",
  "                  Set default options for every search.",
  "                --show-preproc-errors",
  "                  Display a message if preprocessor exits with an error status.",
  "                --past-eof",
  "                  Scrolling commands continue past end of file.",
  "                --proc-backspace",
  "                  Process backspaces for bold/underline.",
  "                --PROC-BACKSPACE",
  "                  Treat backspaces as control characters.",
  "                --proc-return",
  "                  Delete carriage returns before newline.",
  "                --PROC-RETURN",
  "                  Treat carriage returns as control characters.",
  "                --proc-tab",
  "                  Expand tabs to spaces.",
  "                --PROC-TAB",
  "                  Treat tabs as control characters.",
  "                --status-col-width=[_\bN]",
  "                  Set the width of the -J status column to _\bN characters.",
  "                --status-line",
  "                  Highlight or color the entire line containing a mark.",
  "                --use-backslash",
  "                  Subsequent options use backslash as escape char.",
  "                --use-color",
  "                  Enables colored text.",
  "                --wheel-lines=[_\bN]",
  "                  Each click of the mouse wheel moves _\bN lines.",
  "                --wordwrap",
  "                  Wrap lines at spaces.",
  "",
  "",
  " ---------------------------------------------------------------------------",
  "",
  "                          L\bLI\bIN\bNE\bE E\bED\bDI\bIT\bTI\bIN\bNG\bG",
  "",
  "        These keys can be used to edit text being entered ",
  "        on the \"command line\" at the bottom of the screen.",
  "",
  " RightArrow ..................... ESC-l ... Move cursor right one character.",
  " LeftArrow ...................... ESC-h ... Move cursor left one character.",
  " ctrl-RightArrow  ESC-RightArrow  ESC-w ... Move cursor right one word.",
  " ctrl-LeftArrow   ESC-LeftArrow   ESC-b ... Move cursor left one word.",
  " HOME ........................... ESC-0 ... Move cursor to start of line.",
  " END ............................ ESC-$ ... Move cursor to end of line.",
  " BACKSPACE ................................ Delete char to left of cursor.",
  " DELETE ......................... ESC-x ... Delete char under cursor.",
  " ctrl-BACKSPACE   ESC-BACKSPACE ........... Delete word to left of cursor.",
  " ctrl-DELETE .... ESC-DELETE .... ESC-X ... Delete word under cursor.",
  " ctrl-U ......... ESC (MS-DOS only) ....... Delete entire line.",
  " UpArrow ........................ ESC-k ... Retrieve previous command line.",
  " DownArrow ...................... ESC-j ... Retrieve next command line.",
  " TAB ...................................... Complete filename & cycle.",
  " SHIFT-TAB ...................... ESC-TAB   Complete filename & reverse cycle.",
  " ctrl-L ................................... Complete filename, list all.",
  " ---------------------------------------------------------------------------",
  "",
  "        This help is adapted from \"less\" by Mark Nudelman.",
  "        Original: http://greenwoodsoftware.com/less/"
];
