import { inputToString } from "../../src/helpers";

import {
  RED,
  GREEN,
  YELLOW,
  BLUE,
  MAGENTA,
  CYAN,
  BOLD,
  UNDERLINE,
  RESET,
  DIM
} from "./constants";

export const text = [
  '1 A',
  `2 ${RED}ABCD${RESET}`,
  `3 ${BLUE}你好${RESET}`,
  `4 ${BOLD}Lorem ipsum${RESET} dolor sit amet`,
  `5 Hello ${CYAN}こんにちは${RESET} ${YELLOW}안녕하세요${RESET} ${GREEN}你好${RESET} ${MAGENTA}😀😃😄😁😆${RESET}`,
  `6 ${UNDERLINE}abcdefghijklmnopqrstuvwxyz${RESET}ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`,
  `7 ${RED}这是${GREEN}一段${BLUE}中文${RESET}，用于测试宽度显示效果。`,
  `8 ${YELLOW}😀😃😄😁😆😅${RESET}😂🤣😊😇${CYAN}🙂🙃😉😌😍🥰${RESET}😘😗😙😚`,
  `9 ${BOLD}Coding${RESET} is fun! ${GREEN}编程很有趣！${RESET}${BLUE}코딩은 재미있어요！${RESET}${YELLOW}👨‍💻👩‍💻${RESET}`,
  `10 The ${YELLOW}quick brown fox${RESET} jumps over the ${BOLD}lazy dog${RESET}. ${CYAN}快速的棕色狐狸跳过懒狗。${RESET}`,
  `11 ${RED}🌸🌼🌻${RESET}${GREEN}🌺🌹🌷${RESET}${BLUE}🌱🌲🌳${RESET}${YELLOW}🌴🌵🌾${RESET}${MAGENTA}🌿🍀🍁🍂🍃${RESET}`,
  `12 The rain in Spain stays mainly in the plain. ${UNDERLINE}西班牙的雨主要下在平原上。${RESET}`,
  `13 1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ${BOLD}🌈🔥💧❄️🍀🌸${RESET}`,
  `14 ${CYAN}这是一段非常非常长的中文文本${RESET}，用于模拟宽度测试，看看换行逻辑是否正确处理这些复杂的字符。`,
  `15 ${CYAN}🧠🫀🫁🦷🦴${RESET}${MAGENTA}🦿🦾🧬🔬${RESET}${YELLOW}👀👅👄👃👂👣${RESET}${GREEN}🧠🫀🫁🦷🦴🦿🦾🧬${RESET}`,
  `16 ${BOLD}Lorem ipsum dolor sit amet${RESET} consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore`,
  `17 Testing line 17 with a mix of characters: ${RED}汉字${RESET}, Emoji ${YELLOW}🎉🎊${RESET}, and ASCII!`,
  `18 ${DIM}🌍🌎🌏🌐${RESET}🌑🌒🌓🌔${BOLD}🌕🌖🌗🌘${RESET}🌙🌚${CYAN}🌛🌜🌝${RESET}`,
  `19 Mixed: Hello ${BOLD}${CYAN}世界${RESET} ${YELLOW}🌈🔥💧${RESET}${GREEN}❄️🍀🌸${RESET}🌼🌻${MAGENTA}🌺🌹🌷${RESET}🌱🌲🌳`,
  `20 A line with CJK + emoji + ASCII to push the limits: ${GREEN}${BOLD}编程测试${RESET}`,
  `21 hashMap[13]:`,
  `22 ${CYAN}{"key":"apple","value":1}${RESET} -> ${RED}{"key":"cherry","value":5}${RESET} -> ${YELLOW}{"key":"mango","value":7}${RESET} -> ${GREEN}{"key":"strawberry","value":2}${RESET} -> ${BLUE}{"key":"pineapple","value":6}${RESET} -> ${MAGENTA}{"key":"blueberry","value":3}${RESET} -> ${BOLD}{"key":"raspberry","value":10}${RESET} -> ${UNDERLINE}{"key":"blackberry","value":7}${RESET} -> ${DIM}null${RESET}`,
  '23 Another long one: 🧵🧶🪡🪢🪣🪤🪥🪦🪧🪨🪩🪪🪫🪬🪭🪮🪯🪰🪱🪲🪳🪴🪵',
  '24 Hello world! 👋 你好世界！こんにちは世界！안녕하세요 세상! 🌍🌎🌏',
  '25 This is a relatively long ASCII line to balance things out, adding more letters and digits 1234567890.',
  '26 🦕🦖🌪️🧊🔥❄️💧💦🌈⛅☁️🌤️🌞🌛🌜🌚🌝🌎🌍🌏🌐',
  '27 Testing pure CJK: 测试一些不同的中文行来确认显示宽度和换行是否一致。',
  '28 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vel hendrerit libero.',
  '29 📚📖📝✏️🔍🧠💭🎓🏫📊📈🧬🔬⚗️🧪💡🧱🛠️⚙️🖥️💾📦',
  '30 Just text 🧠🫀🫁🦷🦴🦿🦾🦻🧏‍♀️👀👁️👅👄👃👂, nothing special here.',
  '31 混合行包括各种字符和符号，用于终端宽度测试。',
  '32 The line number 30 is where we add a longer message to challenge rendering in edge cases 😺😸😹😻',
  '33 🏞️🌄🌅🌆🌇🌉🌁🌃🌌🌠🌇🌆🏙️🌃🌌✨🌟💫',
  '34 Super wide test line, padding it further and further until we exceed normal expectations... 👨‍👩‍👧‍👦👨‍👩‍👧‍👧👩‍👩‍👧‍👧',
  '35 这是一段非常长的文字，为了确保终端在渲染时不会出错，我们加入足够的内容来测试分页功能是否正常',
  '36 🚀🚀🚀 Testing long emoji-only line 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀',
  '37 Final big mix: ABC汉字🙂🙃😉😌😍🥰😘😗😙😚🤪🤨🧐🤓😎🥸🤩🥳🤗🤔',
  '38 One more to end!!!',
  '39 Just kidding, lets count to 10!',
  '40 1!',
  '41 2!',
  '42 3!',
  '43 4!',
  '44 5!',
  '45 6!',
  '46 7!',
  '47 8!',
  '48 9!',
  '49 10!!!',
  '50 THE END 🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩'
];

export const content = inputToString(text.join('\n'), false);
